# Generated by Django 2.2.1 on 2019-05-23 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название группы ингредиентов', max_length=64)),
                ('type', models.CharField(choices=[('radio', 'Радио-кнопки'), ('input', 'Ввод'), ('checkbox', 'Флажки'), ('select', 'Выпадающий список')], default='input', help_text='Поля выбора', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название ингредиента', max_length=64)),
                ('price', models.PositiveIntegerField(help_text='Цена за еденицу, может быть NULL', null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.Group')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
