# Generated by Django 2.2.1 on 2019-05-23 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='type',
        ),
    ]
