# Generated by Django 2.2.1 on 2019-05-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_remove_group_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='type',
            field=models.CharField(choices=[('radio', 'Радио-кнопки'), ('input', 'Ввод'), ('checkbox', 'Флажки'), ('select', 'Выпадающий список')], default='input', help_text='Поля выбора', max_length=7),
        ),
    ]
