# Generated by Django 2.2.1 on 2019-05-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_group_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='Цена за еденицу, может быть NULL', null=True),
        ),
    ]
