# Generated by Django 2.2.1 on 2019-05-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_auto_20190523_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.FloatField(default=0, help_text='Цена за еденицу, может быть NULL', null=True),
        ),
    ]
