# Generated by Django 2.2.1 on 2019-05-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0007_auto_20190523_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='sort_index',
            field=models.IntegerField(default=5, help_text='Индекс сортировки вывода группы полей'),
        ),
    ]
