# Generated by Django 2.2.1 on 2019-05-24 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0008_group_sort_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['sort_index']},
        ),
    ]
