# Generated by Django 2.2.1 on 2019-05-24 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0009_auto_20190524_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['price']},
        ),
    ]
