# Generated by Django 2.2.1 on 2019-05-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0010_auto_20190524_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.CharField(choices=[('radio', 'Радио-кнопки'), ('number', 'Числовой ввод'), ('checkbox', 'Флажки'), ('select', 'Выпадающий список')], default='input', help_text='Поля выбора', max_length=7),
        ),
    ]
