# Generated by Django 2.2.1 on 2019-05-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0011_auto_20190524_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['price', 'group__name']},
        ),
    ]
